libvpxdec: Fix "error: implicit declaration of function ‘av_check_image_size’".
av_check_image_size() is declared in libavcore/imgutils.h.


git-svn-id: file:///var/local/repositories/ffmpeg/trunk@24717 9553f0bf-9b14-0410-a0b8-cfaf0461ba5b